@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ExerciseBook *-right-> "1" UniqueExerciseList

UniqueExerciseList o-right-> Exercise

Exercise *--> Calories
Exercise *--> Date
Exercise *--> Description
Exercise *--> Name
Exercise --> "*" ExerciseTag
Exercise --> "*" MuscleTag
@enduml
